import {useEffect,useState} from 'react'
import {Link} from 'react-router-dom'
import {ArrowUp,ArrowDown,Trash2} from 'lucide-react'
import {sb,configured,slugify,applyTheme,THEMES,HEADS,BODYS,TEXTS,TEXTS_HI,compress,contrast,DEFAULT_SECTIONS,DEFAULT_MENU,DEFAULT_FORM} from './lib.js'
const up=async f0=>{const f=await compress(f0);const p=`${crypto.randomUUID()}-${f.name.replace(/[^\w.-]/g,'_')}`;const {error}=await sb.storage.from('product-images').upload(p,f,{cacheControl:'31536000',contentType:f.type||'application/octet-stream'});if(error)throw error;return sb.storage.from('product-images').getPublicUrl(p).data.publicUrl}
const T=({children})=><h2 className="mb-4 font-serif text-3xl">{children}</h2>
const uid=()=>crypto.randomUUID()
let LK=null
function useLookups(){const [v,setV]=useState(LK||{cats:[],pages:[]})
useEffect(()=>{if(LK)return;let on=true;Promise.all([sb.from('categories').select('name,slug').order('sort_order'),sb.from('pages').select('title,slug')]).then(([c,p])=>{LK={cats:c.data||[],pages:p.data||[]};if(on)setV(LK)});return()=>{on=false}},[])
return {...v,links:['/','/catalogue','/about','/visit','/contact','/saved',...v.pages.map(p=>'/p/'+p.slug),...v.cats.map(c=>'/category/'+c.slug)]}}
// One small input for any kind of value. Used by the page builder, menu editor and form builder.
function Ctl({x,v,on}){const [m,setM]=useState(''),lk=useLookups(),val=v??''
if(x.t==='textarea')return <textarea className="inp" rows={x.rows||4} value={val} onChange={e=>on(e.target.value)}/>
if(x.t==='select')return <select className="inp" value={val||x.o[0][0]} onChange={e=>on(e.target.value)}>{x.o.map(([a,b])=><option key={a} value={a}>{b}</option>)}</select>
if(x.t==='check')return <input type="checkbox" checked={!!v} onChange={e=>on(e.target.checked)}/>
if(x.t==='number')return <input type="number" className="inp" min={x.min} max={x.max} value={val} onChange={e=>on(e.target.value===''?'':+e.target.value)}/>
if(x.t==='image'||x.t==='media')return <div>{v&&(x.t==='image'?<img src={v} alt="" className="mb-2 h-20"/>:<p className="mb-2 text-xs"><a className="underline" href={v} target="_blank" rel="noreferrer">Current file</a></p>)}{v&&<button type="button" className="mb-2 mr-3 text-xs underline" onClick={()=>on('')}>Remove</button>}<input type="file" accept={x.t==='image'?'image/*':x.acc} onChange={async e=>{const f=e.target.files[0];if(!f)return;if(x.max&&f.size>x.max*1048576){setM(`Too large. Limit ${x.max} MB.`);e.target.value='';return}try{setM('Uploading…');on(await up(f));setM('Uploaded.')}catch(er){setM(er.message)}}}/>{m&&<span className="ml-2 text-xs" role="status">{m}</span>}</div>
if(x.t==='images'){const a=Array.isArray(v)?v:[];return <div><div className="mb-2 flex flex-wrap gap-2">{a.map((u,i)=><div key={u+i} className="relative"><img src={u} alt="" className="h-20 w-20 object-cover"/><button type="button" aria-label="Remove image" className="absolute right-0 top-0 bg-ivory px-1.5" onClick={()=>on(a.filter((_,k)=>k!==i))}>×</button></div>)}</div><input type="file" multiple accept="image/*" onChange={async e=>{const fs=[...e.target.files];try{setM('Uploading…');const urls=[];for(const f of fs)urls.push(await up(f));on([...a,...urls]);setM('Uploaded.')}catch(er){setM(er.message)}}}/>{m&&<span className="ml-2 text-xs" role="status">{m}</span>}</div>}
if(x.t==='list')return <ListEditor value={v} onChange={on} x={x}/>
const dl=x.sugg==='links'?lk.links:null
return <><input className="inp" list={dl?'dl-links':undefined} placeholder={x.ph} value={val} onChange={e=>on(e.target.value)}/>{dl&&<datalist id="dl-links">{dl.map(o=><option key={o} value={o}/>)}</datalist>}</>}
// A list of small records the admin can add to, remove from and reorder (menu items, form fields, cards, FAQ...).
function ListEditor({value,onChange,x}){const a=Array.isArray(value)&&(value.length||!x.fallback)?value:(x.fallback||[])
const mv=(i,j)=>{if(j<0||j>=a.length)return;const b=[...a],[r]=b.splice(i,1);b.splice(j,0,r);onChange(b)},upd=(i,k,v)=>onChange(a.map((r,n)=>n===i?{...r,[k]:v}:r))
return <div className="space-y-3">{a.map((r,i)=><div key={r.id||i} className="border border-sand p-3"><div className="mb-2 flex items-center justify-between text-xs"><span>{x.what} {i+1}{x.title&&r[x.title]?`: ${r[x.title]}`:''}</span><span className="flex gap-3"><button type="button" aria-label="Move up" onClick={()=>mv(i,i-1)}><ArrowUp size={14}/></button><button type="button" aria-label="Move down" onClick={()=>mv(i,i+1)}><ArrowDown size={14}/></button><button type="button" aria-label={`Delete ${x.what}`} onClick={()=>{if(confirm(`Delete this ${x.what.toLowerCase()}?`))onChange(a.filter((_,n)=>n!==i))}}><Trash2 size={14}/></button></span></div>
<div className="grid gap-3 sm:grid-cols-2">{x.cols.filter(c=>!c.if||c.if(r)).map(c=><label key={c.k} className={`block text-xs ${['textarea','image','images','media'].includes(c.t)?'sm:col-span-2':''}`}>{c.l}<div className="mt-1"><Ctl x={c} v={r[c.k]} on={v=>upd(i,c.k,v)}/></div></label>)}</div></div>)}
<div className="flex flex-wrap gap-3"><button type="button" className="btn-sm" onClick={()=>onChange([...a,x.make()])}>+ Add {x.what.toLowerCase()}</button>{x.fallback&&<button type="button" className="text-xs underline" onClick={()=>{if(confirm('Go back to the original list?'))onChange(x.fallback)}}>Reset to original</button>}</div></div>}
const BUILTIN={hero:['Top banner with the big photo','Edit it in the Homepage tab. It is always first.'],categories:['Categories','Edit them in the Categories tab.'],featured:['Featured products','Tick "Show on homepage" on a product in the Products tab.'],marquee:['Big scrolling text band'],carousel:['Scrolling photo carousel','Edit the photos in the Carousel tab.'],story:['Our story (text and photo)','Edit it in the Homepage tab.'],showcase:['Full-width showcase photo','Edit it in the Homepage tab.'],testimonials:['Customer reviews','Edit them in the Testimonials tab.'],cta:['Contact call-to-action','Change its words in the Texts tab.']}
const BT={text:'Heading and text',imagetext:'Photo with text',gallery:'Photo gallery',video:'Video',banner:'Banner with a button',cards:'Cards (features, steps, services)',faq:'Questions and answers',products:'Products',spacer:'Empty space'}
const SCHEMA=cats=>{const B=[{k:'btn_label',l:'Button text (optional)'},{k:'btn_link',l:'Button link',sugg:'links',ph:'/catalogue or https://…'}];return {
text:[{k:'title',l:'Heading'},{k:'align',l:'Alignment',t:'select',o:[['left','Left'],['center','Centre']]},{k:'body',l:'Text',t:'textarea'},...B],
imagetext:[{k:'title',l:'Heading'},{k:'side',l:'Photo position',t:'select',o:[['left','Left'],['right','Right']]},{k:'image',l:'Photo',t:'image'},{k:'body',l:'Text',t:'textarea'},...B],
gallery:[{k:'title',l:'Heading (optional)'},{k:'cols',l:'Photos per row on large screens',t:'select',o:[['2','2'],['3','3'],['4','4']]},{k:'images',l:'Photos',t:'images'}],
video:[{k:'title',l:'Heading (optional)'},{k:'url',l:'YouTube or Vimeo link',ph:'https://www.youtube.com/watch?v=…'},{k:'video',l:'Or upload a video (MP4, up to 45 MB)',t:'media',acc:'video/mp4,video/webm',max:45}],
banner:[{k:'title',l:'Heading'},{k:'image',l:'Background photo',t:'image'},{k:'body',l:'Text',t:'textarea'},...B],
cards:[{k:'title',l:'Heading (optional)'},{k:'items',l:'Cards',t:'list',what:'Card',title:'title',make:()=>({id:uid(),title:'',text:'',image:''}),cols:[{k:'title',l:'Title'},{k:'image',l:'Photo (optional)',t:'image'},{k:'text',l:'Text',t:'textarea',rows:3}]}],
faq:[{k:'title',l:'Heading (optional)'},{k:'items',l:'Questions',t:'list',what:'Question',title:'q',make:()=>({id:uid(),q:'',a:''}),cols:[{k:'q',l:'Question'},{k:'a',l:'Answer',t:'textarea',rows:3}]}],
products:[{k:'title',l:'Heading (optional)'},{k:'category',l:'Which products',t:'select',o:[['featured','Featured products'],['all','All products'],...cats.map(c=>[c.slug,`Category: ${c.name}`])]},{k:'count',l:'How many (1 to 12)',t:'number',min:1,max:12}],
spacer:[{k:'size',l:'Size',t:'select',o:[['sm','Small'],['md','Medium'],['lg','Large']]}]}}
// The page builder: add, remove, reorder and edit sections. Used for the home page layout and for custom pages.
function Blocks({value,onChange,home}){const {cats}=useLookups(),[open,setOpen]=useState(null),[add,setAdd]=useState('text'),[dr,setDr]=useState(null)
const list=Array.isArray(value)&&value.length?value:(home?DEFAULT_SECTIONS:[]),hero=home?(list.find(x=>x.type==='hero')||DEFAULT_SECTIONS[0]):null,body=home?list.filter(x=>x.type!=='hero'):list,S=SCHEMA(cats)
const commit=b=>onChange(home?[hero,...b]:b),mv=(i,j)=>{if(j<0||j>=body.length||i===j)return;const b=[...body],[r]=b.splice(i,1);b.splice(j,0,r);commit(b)},upd=(i,k,v)=>commit(body.map((b,n)=>n===i?{...b,[k]:v}:b))
const addB=()=>{const b={id:uid(),type:add,visible:true};if(add==='products')Object.assign(b,{category:'featured',count:4});commit([...body,b]);setOpen(b.id)}
return <div className="space-y-2"><p className="text-xs opacity-70">Drag a section by its handle, or use the arrows, to move it. Untick Show to hide it without deleting.</p>
{home&&<div className="border border-sand bg-sand/30 p-3 text-sm">Top banner with the big photo <span className="text-xs opacity-70">(always first, edit it in the Homepage tab)</span></div>}
{body.map((b,i)=>{const bi=BUILTIN[b.type],lab=bi?bi[0]:BT[b.type]||b.type;return <div key={b.id} className="border border-sand" onDragOver={e=>e.preventDefault()} onDrop={()=>{if(dr!==null)mv(dr,i);setDr(null)}}>
<div draggable onDragStart={()=>setDr(i)} onDragEnd={()=>setDr(null)} className={`flex flex-wrap items-center gap-3 p-3 ${dr===i?'opacity-40':''}`}><span aria-hidden="true" className="hidden cursor-grab select-none text-earth md:inline">⋮⋮</span><button type="button" className="flex-1 text-left" aria-expanded={open===b.id} onClick={()=>setOpen(open===b.id?null:b.id)}>{lab}{!bi&&b.title?`: ${b.title}`:''}{bi&&<span className="ml-2 text-xs opacity-60">built-in</span>}</button>
<label className="text-xs"><input type="checkbox" className="mr-1" checked={b.visible!==false} onChange={e=>upd(i,'visible',e.target.checked)}/>Show</label><button type="button" aria-label="Move up" onClick={()=>mv(i,i-1)}><ArrowUp size={16}/></button><button type="button" aria-label="Move down" onClick={()=>mv(i,i+1)}><ArrowDown size={16}/></button>{!bi&&<button type="button" aria-label="Delete section" onClick={()=>{if(confirm('Delete this section?'))commit(body.filter((_,n)=>n!==i))}}><Trash2 size={16}/></button>}</div>
{open===b.id&&<div className="grid gap-3 border-t border-sand p-3 sm:grid-cols-2">{bi?(b.type==='marquee'?<label className="block text-xs sm:col-span-2">Text (leave empty to use your business name)<div className="mt-1"><Ctl x={{}} v={b.text} on={v=>upd(i,'text',v)}/></div></label>:<p className="text-sm sm:col-span-2">{bi[1]}</p>):(S[b.type]||[]).map(c=><label key={c.k} className={`block text-xs ${['textarea','image','images','media','list'].includes(c.t)?'sm:col-span-2':''}`}>{c.l}<div className="mt-1"><Ctl x={c} v={b[c.k]} on={v=>upd(i,c.k,v)}/></div></label>)}</div>}</div>})}
<div className="flex flex-wrap items-center gap-3 pt-2"><select aria-label="Section type" className="inp !w-auto" value={add} onChange={e=>setAdd(e.target.value)}>{Object.entries(BT).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select><button type="button" className="btn-sm" onClick={addB}>+ Add section</button></div></div>}
function Editor({table,fields,single,blank={},Extra}){
const [rows,setRows]=useState([]),[f,setF]=useState(null),[m,setM]=useState(''),[dr,setDr]=useState(null),[sel,setSel]=useState([]),isP=table==='products'
const load=async()=>{if(single){const {data}=await sb.from(table).select('*').eq('id',1).maybeSingle();setF(data||{id:1});return}const {data}=await sb.from(table).select('*').order('sort_order');setRows(data||[])}
useEffect(()=>{setF(null);setSel([]);load()},[table])
const save=async e=>{e.preventDefault();setM('Saving…');const r={...f};if(!single&&r.sort_order==null)r.sort_order=rows.length;if(fields.some(x=>x.k==='slug')&&!r.slug)r.slug=slugify(r.name||r.title||'')
const {data,error}=await sb.from(table).upsert(r).select().single();if(error){setM(error.message);return}setF(data);setM('Saved');load()}
const del=async r=>{if(!confirm('Delete this item? This cannot be undone.'))return;await sb.from(table).delete().eq('id',r.id);setF(null);load()}
const reorder=async(i,j)=>{if(j<0||j>=rows.length||i===j)return;const a=[...rows],[x]=a.splice(i,1);a.splice(j,0,x);setRows(a);await Promise.all(a.map((r,k)=>sb.from(table).update({sort_order:k}).eq('id',r.id)));load()}
const bulk=async status=>{if(!sel.length||!confirm(`Set ${sel.length} product(s) to "${status}"?`))return;const {error}=await sb.from('products').update({status}).in('id',sel);setM(error?error.message:'Updated');setSel([]);load()}
const dup=async()=>{setM('Duplicating…');const {id,created_at,...rest}=f;const {data,error}=await sb.from('products').insert({...rest,name:f.name+' (copy)',slug:`${f.slug||slugify(f.name)}-copy-${Math.random().toString(36).slice(2,6)}`,status:'draft',featured:false,sort_order:rows.length}).select().single();if(error){setM(error.message);return}
const [im,sp]=await Promise.all([sb.from('product_images').select('url,sort_order,alt').eq('product_id',id),sb.from('product_specifications').select('label,value,sort_order').eq('product_id',id)])
if(im.data?.length)await sb.from('product_images').insert(im.data.map(r=>({...r,product_id:data.id})))
if(sp.data?.length)await sb.from('product_specifications').insert(sp.data.map(r=>({...r,product_id:data.id})))
setF(data);setM('Duplicated as a draft. You are now editing the copy.');load()}
const fld=x=>{const v=f[x.k]??'',set=val=>{setF(o=>({...o,[x.k]:val}));if(table==='site_settings')applyTheme({...f,[x.k]:val})}
if(x.t==='theme'){const cur=f.theme||'ivory-clay',base=(THEMES.find(t=>t[0]===cur)||THEMES[0]).slice(2),cu=Array.isArray(f.custom_theme)&&f.custom_theme.length===4?f.custom_theme:base,many=o=>{setF(p=>({...p,...o}));applyTheme({...f,...o})},names=['Background','Panels and borders','Accent (links, highlights)','Text']
const card=(id,name,cols,fn)=><button type="button" key={id} onClick={fn} aria-pressed={cur===id} className={`border p-3 text-left ${cur===id?'border-ink ring-2 ring-earth':'border-sand'}`}><span className="flex h-8">{cols.map((c,i)=><i key={i} style={{background:c}} className="flex-1"/>)}</span><span className="mt-2 block text-sm">{name}</span></button>
return <div><div className="grid grid-cols-2 gap-3 sm:grid-cols-3">{THEMES.map(t=>card(t[0],t[1],t.slice(2),()=>many({theme:t[0]})))}{card('custom','Custom colours',cu,()=>many({theme:'custom',custom_theme:cu}))}</div>
{cur==='custom'&&<div className="mt-4 space-y-3 border border-sand p-4"><div className="grid gap-3 sm:grid-cols-2">{names.map((n,i)=><label key={n} className="flex items-center gap-3 text-sm"><input type="color" value={cu[i]} onChange={e=>many({theme:'custom',custom_theme:cu.map((c,k)=>k===i?e.target.value:c)})} className="h-10 w-14 cursor-pointer border-0 bg-transparent p-0"/>{n}<code className="text-xs">{cu[i]}</code></label>)}</div>
{[['Text on background',cu[3],cu[0],4.5],['Accent on background',cu[2],cu[0],3]].map(([n,a,b,min])=>{const r=contrast(a,b);return <p key={n} role="status" className={`text-sm ${r<min?'font-semibold':''}`}>{n}: {r.toFixed(1)} to 1. {r>=min?'Easy to read.':'Hard to read. Choose a stronger colour.'}</p>})}</div>}</div>}
if(x.t==='blocks')return <Blocks value={f[x.k]} onChange={set} home={x.home}/>
if(x.t==='list')return <Ctl x={x} v={f[x.k]} on={set}/>
if(x.t==='textarea')return <textarea className="inp" rows={5} value={v} onChange={e=>set(e.target.value)}/>
if(x.t==='select')return <select className="inp" value={v} onChange={e=>set(e.target.value||null)}>{!x.r&&<option value="">None</option>}{x.o.map(([a,b])=><option key={a} value={a}>{b}</option>)}</select>
if(x.t==='check')return <input type="checkbox" checked={!!f[x.k]} onChange={e=>set(e.target.checked)}/>
if(x.t==='media')return <div>{v&&<p className="mb-2 break-all text-xs"><a className="underline" href={v} target="_blank" rel="noreferrer">Current file</a><button type="button" className="ml-3 underline" onClick={()=>set(null)}>Remove</button></p>}<input type="file" accept={x.acc} onChange={async e=>{const file=e.target.files[0];if(!file)return;if(file.size>x.max*1048576){setM(`That file is too large. The limit is ${x.max} MB.`);e.target.value='';return}try{setM('Uploading, please wait…');set(await up(file));setM('File uploaded. Press Save to keep it.')}catch(er){setM(er.message)}}}/></div>
if(x.t==='image')return <div>{v&&<img src={v} alt="" className="mb-2 h-24"/>}<input type="file" accept="image/*" onChange={async e=>{try{setM('Uploading…');set(await up(e.target.files[0]));setM('Image uploaded. Press Save to keep it.')}catch(er){setM(er.message)}}}/></div>
return <input className="inp" required={x.r} value={v} onChange={e=>set(e.target.value)}/>}
return <div>{!single&&<><button className="btn mb-4" onClick={()=>{setF({...blank});setM('')}}>Add new</button>
{isP&&rows.length>0&&<div className="mb-3 flex flex-wrap items-center gap-2 text-sm"><label className="mr-2"><input type="checkbox" className="mr-1" checked={sel.length===rows.length} onChange={e=>setSel(e.target.checked?rows.map(r=>r.id):[])}/>Select all</label>{sel.length>0&&<>{sel.length} selected:<button className="border border-sand px-3 py-1" onClick={()=>bulk('published')}>Publish</button><button className="border border-sand px-3 py-1" onClick={()=>bulk('draft')}>Make draft</button><button className="border border-sand px-3 py-1" onClick={()=>bulk('archived')}>Archive</button></>}</div>}
{rows.length>1&&<p className="mb-2 text-xs opacity-70">Drag an item up or down to change the order, or use the arrows.</p>}
<ul className="mb-8 divide-y divide-sand border border-sand">{rows.map((r,i)=><li key={r.id} draggable onDragStart={()=>setDr(i)} onDragOver={e=>e.preventDefault()} onDrop={()=>{if(dr!==null)reorder(dr,i);setDr(null)}} onDragEnd={()=>setDr(null)} className={`flex items-center gap-3 p-3 ${dr===i?'opacity-40':''}`}><span aria-hidden="true" className="hidden cursor-grab select-none text-earth md:inline">⋮⋮</span>{isP&&<input type="checkbox" aria-label={`Select ${r.name}`} checked={sel.includes(r.id)} onChange={e=>setSel(a=>e.target.checked?[...a,r.id]:a.filter(x=>x!==r.id))}/>}{r.image_url&&<img src={r.image_url} alt="" className="h-10 w-10 object-cover"/>}<button className="flex-1 text-left" onClick={()=>{setF(r);setM('')}}>{r.name||r.title||r.caption||r.author||'Image'}{r.status&&<span className="ml-2 text-xs text-earth">{r.status}{r.featured?', featured':''}</span>}</button>
<button aria-label="Move up" onClick={()=>reorder(i,i-1)}><ArrowUp size={16}/></button><button aria-label="Move down" onClick={()=>reorder(i,i+1)}><ArrowDown size={16}/></button><button aria-label="Delete" onClick={()=>del(r)}><Trash2 size={16}/></button></li>)}{!rows.length&&<li className="p-3 text-sm">Nothing here yet.</li>}</ul></>}
{f&&<form onSubmit={save} className="max-w-2xl space-y-4">{(isP||table==='pages')&&f.id&&<p className="flex flex-wrap gap-4 text-sm">{f.slug&&<a className="underline" href={`/${isP?'product':'p'}/${f.slug}?preview=1`} target="_blank" rel="noreferrer">Preview (opens the page, even if it is a draft)</a>}{isP&&<button type="button" className="underline" onClick={dup}>Duplicate this product</button>}</p>}
{fields.map(x=>['theme','blocks','list'].includes(x.t)?<div key={x.k} role="group" aria-label={x.l} className="block text-sm">{x.l}<div className="mt-1">{fld(x)}</div></div>:<label key={x.k} className="block text-sm">{x.l}{x.h&&<span className="block text-xs opacity-70">{x.h}</span>}<div className="mt-1">{fld(x)}</div></label>)}<button className="btn">Save changes</button><span className="ml-4 text-sm" role="status">{m}</span>
{Extra&&f.id&&<Extra pid={f.id}/>}</form>}</div>}
function Extra({pid}){
const [im,setIm]=useState([]),[sp,setSp]=useState(''),[m,setM]=useState(''),[dr,setDr]=useState(null)
const load=async()=>{const a=await sb.from('product_images').select('*').eq('product_id',pid).order('sort_order');setIm(a.data||[]);const b=await sb.from('product_specifications').select('*').eq('product_id',pid).order('sort_order');setSp((b.data||[]).map(r=>`${r.label}: ${r.value}`).join('\n'))}
useEffect(()=>{load()},[pid])
const add=async e=>{const fs=[...e.target.files];setM('Uploading…');try{for(const [k,file] of fs.entries())await sb.from('product_images').insert({product_id:pid,url:await up(file),sort_order:im.length+k});setM('')}catch(er){setM(er.message)}load()}
const mv=async(i,j)=>{if(j<0||j>=im.length||i===j)return;const a=[...im],[x]=a.splice(i,1);a.splice(j,0,x);setIm(a);await Promise.all(a.map((r,k)=>sb.from('product_images').update({sort_order:k}).eq('id',r.id)));load()}
const del=async r=>{await sb.from('product_images').delete().eq('id',r.id);load()}
const saveSp=async()=>{await sb.from('product_specifications').delete().eq('product_id',pid);const rows=sp.split('\n').filter(l=>l.includes(':')).map((l,k)=>{const i=l.indexOf(':');return{product_id:pid,label:l.slice(0,i).trim(),value:l.slice(i+1).trim(),sort_order:k}}).filter(r=>r.label&&r.value);if(rows.length)await sb.from('product_specifications').insert(rows);setM('Specifications saved');load()}
return <div className="space-y-4 border-t border-sand pt-6"><T>Images</T><p className="text-sm">The first image is the cover image. Drag photos to reorder them. Type a short description under each photo, it helps Google and visitors who use screen readers.</p><div className="flex flex-wrap gap-3">{im.map((r,i)=><div key={r.id} draggable onDragStart={()=>setDr(i)} onDragOver={e=>e.preventDefault()} onDrop={()=>{if(dr!==null)mv(dr,i);setDr(null)}} className="w-28 cursor-grab"><img src={r.url} alt="" className="h-28 w-28 object-cover"/><input aria-label="Photo description" placeholder="Describe photo" className="inp mt-1 !p-1 text-xs" defaultValue={r.alt||''} onBlur={e=>{if(e.target.value!==(r.alt||''))sb.from('product_images').update({alt:e.target.value||null}).eq('id',r.id)}}/><div className="flex justify-between pt-1"><button type="button" aria-label="Move earlier" onClick={()=>mv(i,i-1)}><ArrowUp size={14}/></button><button type="button" aria-label="Move later" onClick={()=>mv(i,i+1)}><ArrowDown size={14}/></button><button type="button" aria-label="Delete image" onClick={()=>del(r)}><Trash2 size={14}/></button></div></div>)}</div>
<input type="file" multiple accept="image/*" onChange={add}/><T>Specifications</T><p className="text-sm">One per line, like “Material: Teak wood”. Lines such as Material, Colour or Finish become filter options in the catalogue automatically.</p><textarea className="inp" rows={6} value={sp} onChange={e=>setSp(e.target.value)}/><button type="button" className="btn" onClick={saveSp}>Save specifications</button><span className="ml-4 text-sm" role="status">{m}</span></div>}
const CAT=[{k:'name',l:'Category name',r:1},{k:'slug',l:'Web address name (filled in automatically if empty)'},{k:'description',l:'Description',t:'textarea'},{k:'image_url',l:'Image',t:'image'}]
const CAR=[{k:'image_url',l:'Image',t:'image'},{k:'caption',l:'Caption'},{k:'link_url',l:'Link (optional)'},{k:'active',l:'Show on homepage',t:'check'}]
const HOME=[{k:'hero_title',l:'Hero title'},{k:'hero_subtitle',l:'Hero subtitle'},{k:'hero_image_url',l:'Hero image',t:'image'},{k:'story_title',l:'Story title'},{k:'story_body',l:'Story text',t:'textarea'},{k:'story_image_url',l:'Story image',t:'image'},{k:'showcase_image_url',l:'Showcase image (full width)',t:'image'}]
const HERO_EXTRA=[{k:'hero_image_2_url',l:'Hero image 2 (optional slideshow)',t:'image',h:'Add a second and third image to make the top of the home page change slowly by itself.'},{k:'hero_image_3_url',l:'Hero image 3 (optional slideshow)',t:'image'},{k:'hero_video_url',l:'Hero video (optional)',t:'media',acc:'video/mp4,video/webm',max:45,h:'MP4, up to 45 MB, ideally under 15 seconds. It plays silently on top of the hero image. Visitors on data saver or reduced motion see the image instead.'}]
const LAYOUT=[{k:'sections',l:'Sections on the home page, from top to bottom',t:'blocks',home:true}]
const PAGES=[{k:'title',l:'Page title',r:1},{k:'slug',l:'Web address (optional)',h:'Filled in automatically from the title. The page will be at yoursite.com/p/this-address'},{k:'published',l:'Published (visible to visitors)',t:'check'},{k:'blocks',l:'Content of the page',t:'blocks'},{k:'seo_title',l:'Google title (optional)'},{k:'seo_description',l:'Google and WhatsApp description (optional)',t:'textarea'}]
const MENU=[{k:'menu',l:'Menu items (top of the site and footer)',t:'list',what:'Menu item',title:'label',fallback:DEFAULT_MENU,make:()=>({id:uid(),label:'',label_hi:'',link:'',visible:true,footer:true}),cols:[{k:'label',l:'Name shown to visitors',ph:'Leave empty for the default name'},{k:'label_hi',l:'Name in Hindi (optional)'},{k:'link',l:'Where it goes',sugg:'links',ph:'Start typing: /catalogue, /p/care-guide or https://…'},{k:'visible',l:'Show in the top menu',t:'check'},{k:'footer',l:'Show in the footer',t:'check'}]}]
const FORM=[{k:'form_fields',l:'Fields of the Contact form, from top to bottom',t:'list',what:'Form field',title:'label',fallback:DEFAULT_FORM,make:()=>({id:uid(),key:'extra_'+Math.random().toString(36).slice(2,7),type:'text',label:'',required:false,options:''}),cols:[{k:'label',l:'Question / label',ph:'Leave empty for the default wording'},{k:'type',l:'Type of answer',t:'select',o:[['text','Short text'],['textarea','Long text'],['email','Email'],['tel','Phone'],['number','Number'],['date','Date'],['select','Choose from a list'],['checkbox','Tick box']]},{k:'options',l:'Choices, separated by commas',ph:'Sofa, Bed, Table',if:r=>r.type==='select'},{k:'required',l:'Visitor must fill it in',t:'check'}]}]
const TESTI=[{k:'quote',l:'What the customer said',t:'textarea',r:1},{k:'author',l:'Customer name',r:1},{k:'place',l:'City (optional)'},{k:'active',l:'Show on homepage',t:'check'}]
const SITE=[{k:'business_name',l:'Business name'},{k:'phone',l:'Phone'},{k:'email',l:'Email'},{k:'whatsapp',l:'WhatsApp number (with country code)'},{k:'address',l:'Address',t:'textarea'},{k:'hours',l:'Business hours',t:'textarea'},{k:'map_location',l:'Footer map location (full address or place name, as you would type it in Google Maps)'},{k:'about_body',l:'About page text',t:'textarea'}]
const BRAND=[{k:'logo_url',l:'Logo',t:'image',h:'Shown in the top menu instead of the name. Use a PNG with a transparent background that looks good on both light and dark photos. Leave empty to show the business name as text.'},{k:'favicon_url',l:'Favicon (small icon in the browser tab)',t:'image',h:'A square image, at least 64 x 64 pixels.'},{k:'instagram_url',l:'Instagram link',h:'Full link, for example https://instagram.com/yourpage'},{k:'facebook_url',l:'Facebook link'},{k:'youtube_url',l:'YouTube link'},{k:'show_language_toggle',l:'Show English / Hindi switch in the menu',t:'check',h:'Translates buttons, headings and forms. Product names and descriptions stay as you typed them. You can edit the Hindi wording in the Texts tab.'},{k:'announcement_on',l:'Show announcement bar at the top of every page',t:'check'},{k:'announcement_text',l:'Announcement text',h:'For example: Diwali sale: 15% off on all sofas until 5 November'},{k:'announcement_link',l:'Announcement link (optional)',h:'Where the text should lead when clicked, for example https://yoursite.com/catalogue'}]
const SEO=[{k:'seo_title',l:'Home page title in Google (max about 60 characters)',h:'Example: Saloni Furniture | Handcrafted sofas, beds and tables in Durgapur'},{k:'seo_description',l:'Home page description in Google and WhatsApp (max about 160 characters)',t:'textarea'},{k:'og_image_url',l:'Image shown when the link is shared on WhatsApp or Facebook',t:'image',h:'Used for the home page and for any product that has no photo.'}]
const DESIGN=[{k:'theme',l:'Website theme (click one; the site changes instantly, press Save to keep it)',t:'theme'},{k:'heading_font',l:'Heading font',t:'select',r:1,o:HEADS.map(h=>[h[0],h[0]])},{k:'body_font',l:'Body font',t:'select',r:1,o:BODYS.map(h=>[h[0],h[0]])}]
function Products(){const [c,setC]=useState([]);useEffect(()=>{sb.from('categories').select('id,name').order('sort_order').then(({data})=>setC((data||[]).map(x=>[x.id,x.name])))},[])
return <Editor table="products" Extra={Extra} blank={{status:'draft'}} fields={[{k:'name',l:'Product name',r:1},{k:'slug',l:'Web address name (filled in automatically if empty)'},{k:'category_id',l:'Category',t:'select',o:c},{k:'short_description',l:'Short description'},{k:'description',l:'Description',t:'textarea'},{k:'status',l:'Status',r:1,t:'select',o:[['draft','Draft (hidden)'],['published','Published'],['archived','Archived (hidden)']]},{k:'featured',l:'Show on homepage',t:'check'},{k:'badge',l:'Badge (optional)',t:'select',o:[['New','New'],['Made to order','Made to order'],['Bestseller','Bestseller'],['Sale','Sale']]},{k:'price_text',l:'Price (optional)',h:'Type it exactly as you want it shown, for example ₹45,000 or Price on request. Leave empty to hide the price.'},{k:'dimensions',l:'Dimensions (optional)',h:'For example: 210 x 90 x 85 cm (W x D x H)'},{k:'video_url',l:'Product video (optional)',t:'media',acc:'video/mp4,video/webm',max:45,h:'MP4, up to 45 MB. Short videos work best.'},{k:'model_url',l:'3D model for View in your room (optional)',t:'media',acc:'.glb,model/gltf-binary',max:45,h:'A .glb file, up to 45 MB. Visitors can rotate it and, on a phone, place it in their room.'},{k:'seo_title',l:'Google title (optional)',h:'If empty, the product name is used.'},{k:'seo_description',l:'Google and WhatsApp description (optional)',h:'If empty, the short description is used.'}]}/>}
function Texts(){const [t,setT]=useState(null),[m,setM]=useState('')
useEffect(()=>{sb.from('site_settings').select('texts').eq('id',1).maybeSingle().then(({data,error})=>{if(error)setM(error.message);setT(data?.texts||{})})},[])
const save=async e=>{e.preventDefault();const clean=Object.fromEntries(Object.entries(t).filter(([k,v])=>TEXTS[k.replace(/^hi_/,'')]&&typeof v==='string'&&v.trim()));setM('Saving…');const {error}=await sb.from('site_settings').update({texts:clean}).eq('id',1);setM(error?error.message:'Saved. Refresh the website to see the new texts.')}
if(!t)return <p>{m||'Loading…'}</p>
return <form onSubmit={save} className="max-w-3xl space-y-4"><p className="text-sm">Change any wording on the website here. The faded text in each box is the current default. Leave a box empty to keep the default. The Hindi column is used when a visitor switches the site to Hindi (turn this on under Brand).</p>
<div className="grid grid-cols-2 gap-2 text-sm font-medium"><span>English</span><span>हिंदी</span></div>
{Object.entries(TEXTS).map(([k,[l,d]])=><div key={k} className="grid grid-cols-2 gap-2 text-sm"><p className="col-span-2 text-xs opacity-70">{l}</p><input aria-label={l+' in English'} className="inp" placeholder={d} value={t[k]||''} onChange={e=>setT(o=>({...o,[k]:e.target.value}))}/><input aria-label={l+' in Hindi'} className="inp" placeholder={TEXTS_HI[k]||'(uses English)'} value={t['hi_'+k]||''} onChange={e=>setT(o=>({...o,['hi_'+k]:e.target.value}))}/></div>)}
<button className="btn">Save texts</button><button type="button" className="btn btn-o ml-3" onClick={()=>{if(confirm('Clear all your changes and go back to the default texts? Press Save afterwards to keep this.'))setT({})}}>Reset to defaults</button><span className="ml-4 text-sm" role="status">{m}</span></form>}
function Analytics(){const [d,setD]=useState(null),[m,setM]=useState(''),[days,setDays]=useState(30)
useEffect(()=>{setD(null);sb.rpc('analytics_summary',{days}).then(({data,error})=>{if(error)setM(error.message+' (Did you run 005_tier2_tier3.sql?)');setD(data||{})})},[days])
if(!d)return <p>{m||'Loading…'}</p>
const bt=d.by_type||{},cards=[['Product page views',bt.view],['Saved to enquiry list',bt.save],['Enquire button clicks',bt.enquire_click],['WhatsApp clicks',bt.whatsapp_click],['Enquiries received',d.enquiries],['Showroom visit requests',d.visits]],daily=d.daily||[],mx=Math.max(1,...daily.map(x=>x.n))
return <div className="space-y-8">{m&&<p role="alert">{m}</p>}<div className="flex gap-2 text-sm">{[7,30,90].map(n=><button key={n} onClick={()=>setDays(n)} className={`border px-3 py-1 ${days===n?'border-ink bg-ink text-ivory':'border-sand'}`}>Last {n} days</button>)}</div>
<div className="grid grid-cols-2 gap-4 md:grid-cols-3">{cards.map(([a,b])=><div key={a} className="border border-sand p-5"><p className="font-serif text-4xl">{b??0}</p><p className="text-sm">{a}</p></div>)}</div>
{daily.length>0&&<div><h3 className="mb-2 font-serif text-2xl">Product views per day</h3><div className="flex h-32 items-end gap-1 border-b border-sand">{daily.map(x=><div key={x.d} title={`${x.d}: ${x.n}`} style={{height:`${Math.max(4,x.n/mx*100)}%`}} className="min-w-1 flex-1 bg-earth"/>)}</div></div>}
<div><h3 className="mb-2 font-serif text-2xl">Most viewed products</h3>{(d.top||[]).length?<div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b border-sand"><th className="py-2">Product</th><th>Views</th><th>Saved</th><th>Enquire / WhatsApp clicks</th></tr></thead><tbody>{d.top.map(x=><tr key={x.slug} className="border-b border-sand"><td className="py-2">{x.name||x.slug}</td><td>{x.views}</td><td>{x.saves}</td><td>{x.clicks}</td></tr>)}</tbody></table></div>:<p className="text-sm">No visits recorded yet. Numbers appear as visitors open product pages. No personal data is stored.</p>}</div></div>}
const dt=d=>new Date(d).toLocaleString([], {dateStyle:'medium',timeStyle:'short'})
function Enq({onChange}){const [r,setR]=useState(null),[o,setO]=useState(null),[m,setM]=useState(''),[fl,setFl]=useState('all')
const load=async()=>{const {data,error}=await sb.from('enquiries').select('*').order('created_at',{ascending:false});if(error)setM(error.message+' (Did you run 004_owner_features.sql?)');setR(data||[]);onChange?.(( data||[]).filter(x=>x.status==='new').length)}
useEffect(()=>{load()},[])
const patch=async(id,v)=>{const {error}=await sb.from('enquiries').update(v).eq('id',id);setM(error?error.message:'Saved');load()}
const del=async x=>{if(!confirm('Delete this enquiry permanently?'))return;await sb.from('enquiries').delete().eq('id',x.id);setO(null);load()}
if(!r)return <p>{m||'Loading…'}</p>
const list=r.filter(x=>fl==='all'||x.status===fl),wa=p=>(p||'').replace(/\D/g,'')
return <div><div className="mb-4 flex flex-wrap items-center gap-2 text-sm">{['all','new','contacted','closed'].map(k=><button key={k} onClick={()=>setFl(k)} className={`border px-3 py-1 capitalize ${fl===k?'border-ink bg-ink text-ivory':'border-sand'}`}>{k}{k!=='all'&&` (${r.filter(x=>x.status===k).length})`}</button>)}<span role="status" className="ml-2">{m}</span></div>
<ul className="divide-y divide-sand border border-sand">{list.map(x=><li key={x.id}><button className="flex w-full flex-wrap items-center justify-between gap-2 p-3 text-left" aria-expanded={o===x.id} onClick={()=>setO(o===x.id?null:x.id)}><span><b className={x.status==='new'?'font-semibold':'font-normal'}>{x.name}</b>{x.kind==='visit'?<span className="ml-2 border border-earth px-1.5 text-xs uppercase text-earth">Visit {x.visit_date}</span>:x.product&&<span className="ml-2 text-sm text-earth">about {x.product}</span>}</span><span className="text-xs"><span className={`mr-3 border px-2 py-0.5 uppercase ${x.status==='new'?'border-ink bg-ink text-ivory':'border-sand'}`}>{x.status}</span>{dt(x.created_at)}</span></button>
{o===x.id&&<div className="space-y-3 bg-sand/30 p-4 text-sm"><p className="whitespace-pre-line">{x.message}</p><p className="flex flex-wrap gap-x-5 gap-y-1"><a className="underline" href={`mailto:${x.email}`}>{x.email}</a>{x.phone&&<a className="underline" href={`tel:${x.phone}`}>{x.phone}</a>}{wa(x.phone)&&<a className="underline" target="_blank" rel="noreferrer" href={`https://wa.me/${wa(x.phone)}`}>WhatsApp</a>}</p>
<label className="block">Status<select className="inp mt-1 max-w-xs" value={x.status} onChange={e=>patch(x.id,{status:e.target.value})}><option value="new">New</option><option value="contacted">Contacted</option><option value="closed">Closed</option></select></label>
<label className="block">Your private notes (visitors never see these)<textarea className="inp mt-1" rows={3} defaultValue={x.notes||''} onBlur={e=>e.target.value!==(x.notes||'')&&patch(x.id,{notes:e.target.value})}/></label>
<button className="text-xs underline" onClick={()=>del(x)}>Delete this enquiry</button></div>}</li>)}{!list.length&&<li className="p-3 text-sm">No enquiries here yet.</li>}</ul></div>}
function Dash(){const [n,setN]=useState({});useEffect(()=>{(async()=>{const c=async(t,s)=>{let x=sb.from(t).select('*',{count:'exact',head:true});if(s)x=x.eq('status',s);return (await x).count};setN({a:await c('products','published'),b:await c('products','draft'),c:await c('products','archived'),d:await c('categories'),e:await c('enquiries','new')})})()},[])
return <div className="grid grid-cols-2 gap-4 md:grid-cols-5">{[['New enquiries',n.e],['Published products',n.a],['Drafts',n.b],['Archived',n.c],['Categories',n.d]].map(([a,b])=><div key={a} className="border border-sand p-5"><p className="font-serif text-4xl">{b??'–'}</p><p className="text-sm">{a}</p></div>)}</div>}
const HELP={Dashboard:'A quick summary. New enquiries are messages from visitors that you have not marked as contacted yet.',Enquiries:'Every message sent from the Contact form is saved here, even if the email goes to spam. Click one to read it, change its status and add private notes.',Products:'Add a product, press Save, then add photos and specifications below. Set Status to Published to show it on the website. Photos are shrunk automatically when uploaded.',Categories:'Groups such as Sofas or Beds. Use the arrows to change the order on the website.',Carousel:'The photos that scroll on the home page. Untick Show on homepage to hide one without deleting it.',Homepage:'The big picture and words at the top of the home page, and the story section.',Design:'Pick a colour theme and fonts. The site changes right away as a preview; press Save to keep it.','Business settings':'Phone, email, address, hours, WhatsApp number, map location and About page text.','Home layout':'Add, remove and reorder the sections of the home page. You can add photo galleries, videos, FAQs, cards, banners and more. Hide a section with the Show tick.',Pages:'Create extra pages such as Care guide, FAQ or Delivery. Add them to the menu in the Menu tab.',Menu:'Add, remove, rename and reorder the links in the top menu and footer. Link to your own pages, categories or any website.','Contact form':'Add, remove and reorder the questions on the Contact form. Answers to extra questions are added to the message you receive.',Analytics:'Simple, private visitor numbers: which products are viewed, saved and asked about most. No personal data is stored.',Testimonials:'Real customer reviews for the home page. The section stays hidden until you add one.',SEO:'Controls how your website looks in Google and when a link is shared on WhatsApp.'}
export default function Admin(){
const [ses,setSes]=useState(undefined),[nn,setNn]=useState(null),[ok,setOk]=useState(false),[tab,setTab]=useState('Dashboard'),[err,setErr]=useState('')
useEffect(()=>{if(!sb){setSes(null);return}sb.auth.getSession().then(({data})=>setSes(data.session));const {data:l}=sb.auth.onAuthStateChange((_,s)=>setSes(s));return()=>l.subscription.unsubscribe()},[])
useEffect(()=>{if(!ok||!sb)return;sb.from('enquiries').select('*',{count:'exact',head:true}).eq('status','new').then(({count})=>setNn(count))},[ok,tab])
useEffect(()=>{if(!ses){setOk(false);return}sb.from('profiles').select('is_admin').eq('id',ses.user.id).maybeSingle().then(({data})=>setOk(!!data?.is_admin))},[ses])
const login=async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target));const {error}=await sb.auth.signInWithPassword({email:f.email,password:f.password});setErr(error?error.message:'')}
const out=<button className="btn" onClick={()=>sb.auth.signOut()}>Log out</button>
if(!configured)return <p className="p-10">Supabase is not configured. Add your keys to .env (see README).</p>
if(ses===undefined)return null
if(!ses)return <form onSubmit={login} className="mx-auto mt-32 max-w-sm space-y-4 px-6"><h1 className="font-serif text-4xl">Admin login</h1><input name="email" type="email" required className="inp" placeholder="Email" aria-label="Email"/><input name="password" type="password" required className="inp" placeholder="Password" aria-label="Password"/><button className="btn">Log in</button>{err&&<p role="alert">{err}</p>}</form>
if(!ok)return <div className="mx-auto mt-32 max-w-md space-y-4 px-6"><p>This account does not have admin access yet. See the README to grant it.</p>{out}</div>
const tabs={Dashboard:<Dash/>,Enquiries:<Enq onChange={setNn}/>,Analytics:<Analytics/>,Products:<Products/>,Categories:<Editor table="categories" fields={CAT}/>,Carousel:<Editor table="homepage_carousel_items" fields={CAR} blank={{active:true}}/>,Homepage:<Editor table="homepage_settings" single fields={[...HOME,...HERO_EXTRA]}/>,'Home layout':<Editor table="homepage_settings" single fields={LAYOUT}/>,Pages:<Editor table="pages" fields={PAGES} blank={{published:true,blocks:[]}}/>,Menu:<Editor table="site_settings" single fields={MENU}/>,'Contact form':<Editor table="site_settings" single fields={FORM}/>, Testimonials:<Editor table="testimonials" fields={TESTI} blank={{active:true}}/>,Design:<Editor table="site_settings" single fields={DESIGN}/>,Brand:<Editor table="site_settings" single fields={BRAND}/>,Texts:<Texts/>,SEO:<Editor table="site_settings" single fields={SEO}/>,'Business settings':<Editor table="site_settings" single fields={SITE}/>}
return <div className="mx-auto max-w-5xl px-6 py-10"><div className="mb-8 flex flex-wrap items-center justify-between gap-4"><Link to="/" className="font-serif text-2xl">Saloni Furniture admin</Link>{out}</div>
<nav className="mb-8 flex flex-wrap gap-2">{Object.keys(tabs).map(t=><button key={t} onClick={()=>setTab(t)} className={`border px-4 py-1.5 text-sm ${tab===t?'border-ink bg-ink text-ivory':'border-sand'}`}>{t}{t==='Enquiries'&&nn>0&&<span className="ml-2 rounded-full bg-earth px-1.5 text-xs text-ivory">{nn}</span>}</button>)}</nav><T>{tab==='Design'?'Theme and fonts':tab==='Brand'?'Logo, social links and announcement bar':tab==='Texts'?'Website texts':tab==='SEO'?'Google and WhatsApp preview':tab==='Testimonials'?'Customer reviews':tab}</T>{HELP[tab]&&<p className="mb-6 max-w-2xl text-sm opacity-80">{HELP[tab]}</p>}<div key={tab}>{tabs[tab]}</div></div>}
