import {Fragment,useEffect,useRef,useState} from 'react'
import {Link,useParams,useSearchParams} from 'react-router-dom'
import {motion,AnimatePresence,useScroll,useTransform,useMotionValue,useSpring} from 'framer-motion'
import {X,Phone,Mail,MapPin,Clock,MessageCircle,Heart} from 'lucide-react'
import {useT,useSEO,useList,sendEnquiry,track,useAsync,useSite,getHome,getCats,getProducts,getCarousel,getProduct,getTestimonials,getPage,DEFAULT_SECTIONS,DEFAULT_FORM,isExt,embedUrl,cover,coverAlt,sorted,PH} from './lib.js'
const E=[.22,1,.36,1]
const fix=e=>{e.currentTarget.src=PH}
const Pg=({children})=><div className="mx-auto max-w-7xl px-6 pb-24 pt-32 md:px-12">{children}</div>
const Img=({src,alt,className=''})=>{const [ok,setOk]=useState(false),r=useRef(null);useEffect(()=>{if(r.current?.complete)setOk(true)},[src])
return <motion.div className={`overflow-hidden bg-sand ${ok?'':'animate-pulse'} ${className}`} initial={{clipPath:'inset(0 0 100% 0)'}} whileInView={{clipPath:'inset(0 0 0% 0)'}} viewport={{once:true,margin:'-40px'}} transition={{duration:1,ease:E}}><img ref={r} src={src||PH} alt={alt||''} loading="lazy" onLoad={()=>setOk(true)} onError={e=>{fix(e);setOk(true)}} className={`h-full w-full object-cover transition-[transform,filter] duration-[900ms] ease-out group-hover:scale-105 ${ok?'':'scale-105 blur-md'}`}/></motion.div>}
const Sk=({n=4})=><div className="grid grid-cols-2 gap-x-4 gap-y-10 lg:grid-cols-4 lg:gap-x-6" aria-hidden="true">{Array.from({length:n},(_,i)=><div key={i}><div className="aspect-[4/5] animate-pulse bg-sand"/><div className="mt-3 h-5 w-2/3 animate-pulse bg-sand"/><div className="mt-2 h-4 w-1/3 animate-pulse bg-sand"/></div>)}</div>
const Card=({p,i=0})=>{const im=sorted(p.product_images),L=useList(),t=useT(),on=L.has(p.slug);return <motion.div className="relative" initial={{opacity:0,y:30}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{duration:.6,delay:(i%4)*.08,ease:E}}><Link to={`/product/${p.slug}`} data-cursor={t('cursor_view')} className="group block"><Tilt className="relative"><Img src={cover(p)} alt={coverAlt(p)} className="aspect-[4/5]"/>{im[1]&&<img src={im[1].url} alt="" loading="lazy" onError={fix} className="pointer-events-none absolute inset-0 h-full w-full object-cover opacity-0 transition-opacity duration-500 group-hover:opacity-100"/>}{p.badge&&<span className="absolute left-3 top-3 bg-ivory px-2 py-1 text-xs uppercase tracking-wider text-ink">{p.badge}</span>}</Tilt><h3 className="mt-3 font-serif text-xl underline-offset-4 group-hover:underline md:text-2xl">{p.name}</h3><p className="text-sm text-earth">{p.categories?.name}{p.price_text&&<span className="text-ink"> · {p.price_text}</span>}</p></Link>
<button type="button" aria-pressed={on} aria-label={on?t('saved_btn'):t('save_btn')} onClick={()=>{L.toggle(p);if(!on)track('save',p)}} className="absolute right-3 top-3 grid h-9 w-9 place-items-center rounded-full bg-ivory/90 text-ink shadow"><Heart size={16} fill={on?'currentColor':'none'}/></button></motion.div>}
const NoMotion=()=>typeof matchMedia!=='undefined'&&(matchMedia('(prefers-reduced-motion:reduce)').matches||!!navigator.connection?.saveData)
function HeroMedia({h,y,x}){const im=[h.hero_image_url,h.hero_image_2_url,h.hero_image_3_url].filter(Boolean),[k,setK]=useState(0),calm=NoMotion()
useEffect(()=>{if(im.length<2||calm)return;const id=setInterval(()=>setK(x=>(x+1)%im.length),6000);return()=>clearInterval(id)},[im.length,calm])
const list=im.length?im:[PH]
return <motion.div style={{y,x}} className="absolute -inset-x-6 -top-10 h-[115%]">{list.map((u,i)=><img key={i} src={u} alt="" onError={fix} loading={i===0?'eager':'lazy'} className={`absolute inset-0 h-full w-full object-cover transition-opacity duration-[1400ms] ${i===k?'opacity-70':'opacity-0'}`}/>)}{h.hero_video_url&&!calm&&<video src={h.hero_video_url} poster={list[0]} autoPlay muted loop playsInline preload="metadata" className="absolute inset-0 h-full w-full object-cover opacity-70"/>}</motion.div>}
const mvLoad=()=>customElements.get('model-viewer')?Promise.resolve():new Promise((res,rej)=>{let el=document.getElementById('mv-js');if(!el){el=document.createElement('script');el.id='mv-js';el.type='module';el.src='https://ajax.googleapis.com/ajax/libs/model-viewer/4.0.0/model-viewer.min.js';document.head.appendChild(el)}el.addEventListener('error',rej);customElements.whenDefined('model-viewer').then(res)})
function ModelView({src,name,poster,label}){const [on,setOn]=useState(false),[er,setEr]=useState(false)
useEffect(()=>{if(on)mvLoad().catch(()=>setEr(true))},[on])
if(!on)return <button type="button" className="btn btn-o mt-3 w-full" onClick={()=>setOn(true)}>{label}</button>
if(er)return <p className="mt-3 text-sm" role="alert">The 3D viewer could not be loaded. Please check your connection.</p>
return <model-viewer src={src} alt={`3D model of ${name}`} poster={poster} camera-controls auto-rotate ar ar-modes="webxr scene-viewer quick-look" shadow-intensity="1" style={{width:'100%',height:'min(70vw,460px)',background:'var(--color-sand)',marginTop:'.75rem'}}><button slot="ar-button" className="btn-sm absolute bottom-3 right-3">{label}</button></model-viewer>}
const Head=({n,t,to,more})=><div className="mb-10 flex items-end justify-between gap-4 border-b border-sand pb-4"><h2 className="overflow-hidden pb-1 font-serif text-4xl md:text-6xl"><motion.span className="block" initial={{y:'105%'}} whileInView={{y:0}} viewport={{once:true,margin:'-40px'}} transition={{duration:.9,ease:E}}>{n&&<span className="mr-3 align-top font-sans text-sm text-earth">{n}</span>}{t}</motion.span></h2>{to&&<Link to={to} className="u shrink-0 pb-2 text-sm">{more}</Link>}</div>
const fine=()=>typeof matchMedia!=='undefined'&&matchMedia('(hover:hover) and (pointer:fine)').matches&&!matchMedia('(prefers-reduced-motion:reduce)').matches
const Reveal=({children,d=0,className=''})=><motion.div className={className} initial={{opacity:0,y:36}} whileInView={{opacity:1,y:0}} viewport={{once:true,margin:'-60px'}} transition={{duration:.9,delay:d,ease:E}}>{children}</motion.div>
function Parallax({src,alt,className='',amt=8}){const r=useRef(null),{scrollYProgress}=useScroll({target:r,offset:['start end','end start']}),y=useTransform(scrollYProgress,[0,1],[`-${amt}%`,`${amt}%`]),calm=NoMotion()
return <div ref={r} className={`overflow-hidden bg-sand ${/absolute/.test(className)?'':'relative'} ${className}`}><motion.img src={src||PH} alt={alt||''} onError={fix} loading="lazy" style={calm?undefined:{y}} className="absolute inset-x-0 -top-[12%] h-[124%] w-full object-cover"/></div>}
function Tilt({children,className=''}){const ok=fine(),x=useMotionValue(0),y=useMotionValue(0),rx=useSpring(useTransform(y,[-.5,.5],[5,-5]),{stiffness:200,damping:20}),ry=useSpring(useTransform(x,[-.5,.5],[-5,5]),{stiffness:200,damping:20})
if(!ok)return <div className={className}>{children}</div>
return <motion.div className={className} style={{rotateX:rx,rotateY:ry,transformPerspective:900}} onMouseMove={e=>{const r=e.currentTarget.getBoundingClientRect();x.set((e.clientX-r.left)/r.width-.5);y.set((e.clientY-r.top)/r.height-.5)}} onMouseLeave={()=>{x.set(0);y.set(0)}}>{children}</motion.div>}
function ScrollMarquee({text}){const r=useRef(null),{scrollYProgress}=useScroll({target:r,offset:['start end','end start']}),x=useTransform(scrollYProgress,[0,1],['8%','-38%']),txt=(text||'').trim(),calm=NoMotion()
if(!txt)return null
return <section ref={r} aria-hidden="true" className="overflow-hidden border-y border-sand py-8 md:py-12"><motion.div style={calm?undefined:{x}} className="flex w-max gap-12 whitespace-nowrap font-serif text-6xl italic md:text-9xl">{Array.from({length:6},(_,i)=><span key={i} className={i%2?'outline-text':''}>{txt} <span className="text-earth">✦</span></span>)}</motion.div></section>}
function Carousel({car}){const ref=useRef(null),half=car?.length?Array(Math.ceil(8/car.length)).fill(car).flat():[],loop=[...half,...half]
useEffect(()=>{if(!ref.current||NoMotion()||!ref.current.getAnimations)return;let last=scrollY,rate=1,raf;const on=()=>{const d=scrollY-last;last=scrollY;rate=Math.max(-5,Math.min(7,rate+d*.12))}
const tick=()=>{rate+=(1-rate)*.06;const a=ref.current?.getAnimations()[0];if(a)a.playbackRate=Math.abs(rate-1)<.02?1:rate;raf=requestAnimationFrame(tick)}
addEventListener('scroll',on,{passive:true});raf=requestAnimationFrame(tick);return()=>{removeEventListener('scroll',on);cancelAnimationFrame(raf)}},[car])
if(!loop.length)return null
return <section className="overflow-hidden border-y border-sand py-10"><div ref={ref} className="marquee flex w-max gap-6">{loop.map((c,i)=>{const B=<figure className="w-64 shrink-0 md:w-80"><img src={c.image_url} alt={c.caption||''} onError={fix} className="aspect-[4/3] w-full object-cover"/>{c.caption&&<figcaption className="mt-2 text-sm">{c.caption}</figcaption>}</figure>;return c.link_url?<a key={i} href={c.link_url}>{B}</a>:<div key={i}>{B}</div>})}</div></section>}
function Mag({children}){const ok=typeof matchMedia!=='undefined'&&matchMedia('(hover:hover) and (pointer:fine)').matches&&!matchMedia('(prefers-reduced-motion:reduce)').matches
const x=useMotionValue(0),y=useMotionValue(0),sx=useSpring(x,{stiffness:220,damping:18}),sy=useSpring(y,{stiffness:220,damping:18})
if(!ok)return children
return <motion.span style={{x:sx,y:sy,display:'inline-block'}} onMouseMove={e=>{const r=e.currentTarget.getBoundingClientRect();x.set((e.clientX-r.left-r.width/2)*.22);y.set((e.clientY-r.top-r.height/2)*.22)}} onMouseLeave={()=>{x.set(0);y.set(0)}}>{children}</motion.span>}
function HeroSec({h}){const s=useSite(),t=useT(),{scrollY}=useScroll(),y=useTransform(scrollY,[0,900],[0,180]),mx=useMotionValue(0),my=useMotionValue(0),sx=useSpring(mx,{stiffness:60,damping:20}),sy=useSpring(my,{stiffness:60,damping:20}),bx=useTransform(sx,v=>v*-18),tx=useTransform(sx,v=>v*10),ty=useTransform(sy,v=>v*6),fp=fine()
const a=d=>({initial:{y:50,opacity:0},animate:{y:0,opacity:1},transition:{duration:1,delay:d,ease:E}})
return <section onMouseMove={e=>{if(!fp)return;mx.set(e.clientX/innerWidth-.5);my.set(e.clientY/innerHeight-.5)}} className="relative h-[100svh] min-h-[560px] overflow-hidden bg-[#1b1916] text-[#f6f1e7]">
<HeroMedia h={h} y={y} x={fp?bx:undefined}/><div className="absolute inset-0 bg-black/30"/>
<motion.div style={fp?{x:tx,y:ty}:undefined} className="relative mx-auto flex h-full max-w-7xl flex-col justify-end px-6 pb-14 md:px-12 md:pb-20">
<h1 className="max-w-5xl font-serif text-5xl leading-[1.02] md:text-8xl">{(h.hero_title||s.business_name||'Saloni Furniture').split(' ').map((w,i)=><span key={i} className="mr-[.25em] inline-block overflow-hidden pb-[.1em] align-bottom"><motion.span className="inline-block" initial={{y:'110%'}} animate={{y:0}} transition={{duration:1,delay:.15+i*.07,ease:E}}>{w}</motion.span></span>)}</h1>
{h.hero_subtitle&&<motion.p {...a(.5)} className="mt-5 max-w-xl text-lg font-light text-[#f6f1e7]/85">{h.hero_subtitle}</motion.p>}
<motion.div {...a(.7)}><Mag><Link to="/catalogue" className="btn btn-l mt-8">{t('hero_cta')}</Link></Mag></motion.div>
<motion.span aria-hidden="true" className="absolute bottom-0 right-12 hidden h-16 w-px origin-top bg-[#f6f1e7]/60 md:block" animate={{scaleY:[0,1,0]}} transition={{repeat:Infinity,duration:2.6,ease:'easeInOut'}}/></motion.div></section>}
export function Home(){
const s=useSite(),t=useT();const {d:h0}=useAsync(getHome),{d:cats}=useAsync(getCats),{d:prods,l:pl}=useAsync(getProducts),{d:car}=useAsync(getCarousel),{d:tm}=useAsync(getTestimonials)
const h=h0||{},feat=(prods||[]).filter(p=>p.featured).slice(0,8)
const secs=(Array.isArray(h.sections)&&h.sections.length?h.sections:DEFAULT_SECTIONS).filter(x=>x.visible!==false&&x.type!=='hero')
const R={
categories:()=>cats?.length>0&&<section className="mx-auto max-w-7xl px-6 py-24 md:px-12"><Head n="01" t={t('cat_heading')} to="/catalogue" more={t('view_all')}/>
<div className="grid grid-cols-2 gap-4 lg:grid-cols-4 lg:gap-6">{cats.slice(0,4).map((c,i)=><Reveal key={c.id} d={i*.08}><Link to={`/category/${c.slug}`} data-cursor={t('cursor_explore')} className="group block"><Img src={c.image_url} alt={c.name} className="aspect-[3/4]"/><h3 className="mt-3 font-serif text-xl md:text-2xl">{c.name}<span aria-hidden="true" className="ml-2 inline-block -translate-x-2 opacity-0 transition duration-500 group-hover:translate-x-0 group-hover:opacity-100">→</span></h3></Link></Reveal>)}</div></section>,
featured:()=><>{pl&&<section className="mx-auto max-w-7xl px-6 pb-24 md:px-12"><Sk/></section>}{feat.length>0&&<section className="mx-auto max-w-7xl px-6 pb-24 md:px-12"><Head n="02" t={t('feat_heading')} to="/catalogue" more={t('view_all')}/><div className="grid grid-cols-2 gap-x-4 gap-y-10 lg:grid-cols-4 lg:gap-x-6">{feat.map((p,i)=><Card key={p.id} p={p} i={i}/>)}</div></section>}</>,
marquee:x=><ScrollMarquee text={x.text||s.business_name||'Saloni Furniture'}/>,
carousel:()=><Carousel car={car}/>,
story:()=>(h.story_title||h.story_body)&&<section className="mx-auto grid max-w-7xl items-center gap-12 px-6 py-24 md:grid-cols-2 md:px-12">{h.story_image_url&&<Parallax src={h.story_image_url} className="aspect-[4/5]"/>}<Reveal d={.1}><h2 className="font-serif text-4xl md:text-6xl">{h.story_title}</h2><p className="mt-6 max-w-prose whitespace-pre-line font-light leading-relaxed">{h.story_body}</p></Reveal></section>,
showcase:()=>h.showcase_image_url&&<Parallax src={h.showcase_image_url} className="h-[70vh] w-full" amt={12}/>,
testimonials:()=>tm?.length>0&&<section className="mx-auto max-w-7xl px-6 py-24 md:px-12"><Head t={t('testi_heading')}/><div className="grid gap-6 md:grid-cols-3">{tm.slice(0,6).map((x,i)=><Reveal key={x.id} d={i*.08}><figure className="h-full border border-sand p-6"><blockquote className="font-serif text-xl leading-snug">“{x.quote}”</blockquote><figcaption className="mt-4 text-sm text-earth">{x.author}{x.place&&`, ${x.place}`}</figcaption></figure></Reveal>)}</div></section>,
cta:()=><section className="bg-band px-6 py-28 text-center text-bandfg"><Reveal><h2 className="mx-auto max-w-3xl font-serif text-4xl md:text-6xl">{t('cta_heading')}</h2><Mag><Link to="/contact" className="btn btn-l mt-10">{t('cta_button')}</Link></Mag></Reveal></section>}
return <><HeroSec h={h}/>{secs.map(x=><Fragment key={x.id}>{R[x.type]?R[x.type](x):<BlockView b={x}/>}</Fragment>)}</>}
const Sec=({children,className=''})=><section className={`mx-auto max-w-7xl px-6 py-14 md:px-12 md:py-20 ${className}`}>{children}</section>
const BtnLink=({b,light})=>{if(!b.btn_label||!b.btn_link)return null;const c=`btn mt-8 ${light?'btn-l':''}`;return <Mag>{isExt(b.btn_link)?<a className={c} href={b.btn_link} {...(/^https?:/i.test(b.btn_link)?{target:'_blank',rel:'noreferrer'}:{})}>{b.btn_label}</a>:<Link className={c} to={b.btn_link}>{b.btn_label}</Link>}</Mag>}
const GC={2:'md:grid-cols-2',3:'md:grid-cols-3',4:'md:grid-cols-4'}
function ProductsBlock({b}){const {d:all,l}=useAsync(getProducts);let list=all||[];if(b.category==='featured')list=list.filter(p=>p.featured);else if(b.category&&b.category!=='all')list=list.filter(p=>p.categories?.slug===b.category);list=list.slice(0,Math.max(1,+b.count||4))
if(l)return <Sec><Sk/></Sec>;if(!list.length)return null
return <Sec>{b.title&&<Head t={b.title}/>}<div className="grid grid-cols-2 gap-x-4 gap-y-10 lg:grid-cols-4 lg:gap-x-6">{list.map((p,i)=><Card key={p.id} p={p} i={i}/>)}</div></Sec>}
function BlockView({b}){const c=b.align==='center'
switch(b.type){
case 'text':return <Sec className={c?'text-center':''}><Reveal>{b.title&&<h2 className="font-serif text-4xl md:text-6xl">{b.title}</h2>}{b.body&&<p className={`mt-6 max-w-prose whitespace-pre-line font-light leading-relaxed ${c?'mx-auto':''}`}>{b.body}</p>}<BtnLink b={b}/></Reveal></Sec>
case 'imagetext':return <Sec><div className="grid items-center gap-10 md:grid-cols-2 md:gap-16">{b.image&&<Reveal className={b.side==='right'?'md:order-2':''}><Parallax src={b.image} alt={b.title} className="aspect-[4/5]"/></Reveal>}<Reveal d={.1}>{b.title&&<h2 className="font-serif text-4xl md:text-6xl">{b.title}</h2>}{b.body&&<p className="mt-6 max-w-prose whitespace-pre-line font-light leading-relaxed">{b.body}</p>}<BtnLink b={b}/></Reveal></div></Sec>
case 'gallery':return <Sec>{b.title&&<Head t={b.title}/>}<div className={`grid grid-cols-2 gap-3 md:gap-5 ${GC[b.cols]||GC[3]}`}>{(b.images||[]).map((u,i)=><Reveal key={i} d={(i%4)*.06}><div className="group"><Img src={u} className="aspect-square"/></div></Reveal>)}</div></Sec>
case 'video':{const em=embedUrl(b.url);return <Sec>{b.title&&<Head t={b.title}/>}<Reveal>{em?<div className="aspect-video"><iframe src={em} title={b.title||'Video'} loading="lazy" allowFullScreen className="h-full w-full border-0"/></div>:b.video?<video src={b.video} controls playsInline preload="metadata" className="w-full bg-black"/>:null}</Reveal></Sec>}
case 'banner':return <section className="relative isolate overflow-hidden bg-[#1b1916] text-[#f6f1e7]">{b.image&&<Parallax src={b.image} className="absolute inset-0 -z-10 opacity-60" amt={10}/>}<div className="mx-auto max-w-4xl px-6 py-24 text-center md:py-36"><Reveal>{b.title&&<h2 className="font-serif text-4xl md:text-6xl">{b.title}</h2>}{b.body&&<p className="mx-auto mt-5 max-w-xl whitespace-pre-line text-lg font-light">{b.body}</p>}<BtnLink b={b} light/></Reveal></div></section>
case 'cards':return <Sec>{b.title&&<Head t={b.title}/>}<div className="grid gap-6 md:grid-cols-3">{(b.items||[]).map((it,i)=><Reveal key={it.id||i} d={(i%3)*.08}><div className="h-full border border-sand p-6">{it.image&&<img src={it.image} alt="" loading="lazy" onError={fix} className="mb-4 aspect-[4/3] w-full object-cover"/>}<h3 className="font-serif text-2xl">{it.title}</h3><p className="mt-2 whitespace-pre-line font-light">{it.text}</p></div></Reveal>)}</div></Sec>
case 'faq':return <Sec>{b.title&&<Head t={b.title}/>}<div className="max-w-3xl border-t border-sand">{(b.items||[]).map((it,i)=><details key={it.id||i} className="faq border-b border-sand py-5"><summary className="flex items-center justify-between gap-4 font-serif text-2xl">{it.q}<span aria-hidden="true" className="plus text-3xl transition-transform">+</span></summary><p className="mt-3 max-w-prose whitespace-pre-line font-light">{it.a}</p></details>)}</div></Sec>
case 'products':return <ProductsBlock b={b}/>
case 'spacer':return <div aria-hidden="true" style={{height:{sm:'2rem',md:'5rem',lg:'9rem'}[b.size||'md']}}/>
default:return null}}
export function CustomPage(){const {slug}=useParams(),[sp]=useSearchParams(),prev=sp.get('preview')==='1',s=useSite();const {d:p,l}=useAsync(()=>getPage(slug,prev),[slug,prev])
useSEO(p?`${p.seo_title||p.title} | ${s.business_name||'Saloni Furniture'}`:'',p?.seo_description||'','')
if(l)return <Pg><p>Loading…</p></Pg>;if(!p)return <NotFound/>
return <>{prev&&<p className="bg-sand px-6 pt-28 text-center text-sm">Preview mode. This page is {p.published?'published':'a draft'}.</p>}<div className={`mx-auto max-w-7xl px-6 md:px-12 ${prev?'pt-8':'pt-32'}`}><h1 className="font-serif text-5xl md:text-7xl">{p.title}</h1></div>{(Array.isArray(p.blocks)?p.blocks:[]).filter(b=>b.visible!==false).map(b=><BlockView key={b.id} b={b}/>)}<div className="pb-16"/></>}
export function Catalogue(){
const {slug}=useParams(),t=useT(),s=useSite();const {d:cats}=useAsync(getCats),{d:all,l}=useAsync(getProducts);const [q,setQ]=useState(''),[sel,setSel]=useState({});useEffect(()=>setSel({}),[slug])
const inCat=(all||[]).filter(p=>!slug||p.categories?.slug===slug),fac={}
inCat.forEach(p=>(p.product_specifications||[]).forEach(x=>{const k=(x.label||'').trim(),v=(x.value||'').trim();if(!k||!v||v.length>40)return;const o=fac[k]||(fac[k]={vals:{},n:0});o.n++;(o.vals[v.toLowerCase()]||(o.vals[v.toLowerCase()]={n:v}))}))
const facets=Object.entries(fac).filter(([,o])=>o.n>=2&&Object.keys(o.vals).length>=2&&Object.keys(o.vals).length<=12).sort((a,b)=>b[1].n-a[1].n).slice(0,4)
const list=inCat.filter(p=>(p.name+' '+(p.short_description||'')).toLowerCase().includes(q.toLowerCase())&&Object.entries(sel).every(([k,v])=>(p.product_specifications||[]).some(x=>x.label.trim()===k&&x.value.trim().toLowerCase()===v)))
const cur=(cats||[]).find(c=>c.slug===slug),ann=s.announcement_on&&s.announcement_text
useSEO(cur?`${cur.name} | ${s.business_name||'Saloni Furniture'}`:'',cur?.description||'',cur?.image_url||'')
return <Pg><h1 className="font-serif text-5xl md:text-7xl">{cur?.name||t('catalogue_heading')}</h1>{cur?.description&&<p className="mt-4 max-w-prose font-light">{cur.description}</p>}
<div className={`my-8 flex flex-col gap-4 bg-ivory py-3 md:sticky ${ann?'md:top-24':'md:top-16'} md:z-30 md:flex-row md:items-center md:justify-between`}><div className="flex gap-2 overflow-x-auto pb-1 md:flex-wrap md:overflow-visible"><Link to="/catalogue" className={`shrink-0 whitespace-nowrap border px-4 py-1.5 text-sm ${!slug?'border-ink bg-ink text-ivory':'border-sand'}`}>{t('cat_all')}</Link>{(cats||[]).map(c=><Link key={c.id} to={`/category/${c.slug}`} className={`shrink-0 whitespace-nowrap border px-4 py-1.5 text-sm ${slug===c.slug?'border-ink bg-ink text-ivory':'border-sand'}`}>{c.name}</Link>)}</div>
<input className="inp md:max-w-xs" placeholder={t('search_ph')} aria-label="Search products" value={q} onChange={e=>setQ(e.target.value)}/></div>
{facets.length>0&&<div className="mb-6 flex flex-wrap items-center gap-3">{facets.map(([k,o])=><select key={k} aria-label={k} className="inp !w-auto" value={sel[k]||''} onChange={e=>setSel(v=>{const n={...v};if(e.target.value)n[k]=e.target.value;else delete n[k];return n})}><option value="">{k}: {t('cat_all')}</option>{Object.entries(o.vals).map(([lk,x])=><option key={lk} value={lk}>{x.n}</option>)}</select>)}{Object.keys(sel).length>0&&<button type="button" className="text-sm underline" onClick={()=>setSel({})}>{t('filters_clear')}</button>}</div>}
{!l&&<p className="mb-6 text-sm text-earth">{list.length} {list.length===1?'piece':'pieces'}</p>}{l?<Sk n={8}/>:!list.length?<p>{t('no_products')}</p>:<div className="grid grid-cols-2 gap-x-4 gap-y-10 lg:grid-cols-4 lg:gap-x-6">{list.map((p,i)=><Card key={p.id} p={p} i={i}/>)}</div>}</Pg>}
export function Product(){
const {slug}=useParams(),t=useT(),L=useList(),[sp]=useSearchParams(),prev=sp.get('preview')==='1';const s=useSite();const {d:all}=useAsync(getProducts);const {d:p,l}=useAsync(()=>getProduct(slug,prev),[slug,prev]);const [i,setI]=useState(0),[box,setBox]=useState(false)
useEffect(()=>{if(p&&!prev)track('view',p)},[p?.id])
useSEO(p?`${p.seo_title||p.name} | ${s.business_name||'Saloni Furniture'}`:'',p?(p.seo_description||p.short_description||(p.description||'').slice(0,180)):'',p?sorted(p.product_images)[0]?.url:'')
if(l)return <Pg><p>Loading…</p></Pg>;if(!p)return <NotFound/>
const ims=sorted(p.product_images),im=ims.map(x=>x.url),rows=[...(p.dimensions?[{label:t('dimensions_label'),value:p.dimensions}]:[]),...sorted(p.product_specifications||[])],on=L.has(p.slug);if(!im.length)im.push(PH)
const wa=(s.whatsapp||'').replace(/\D/g,''),rel=(all||[]).filter(x=>x.id!==p.id&&p.category_id&&x.category_id===p.category_id).slice(0,4)
return <Pg>{prev&&<p className="mb-6 bg-sand p-3 text-sm">Preview mode. This product is <b>{p.status}</b>; visitors only see it when its status is Published.</p>}<div className="grid gap-10 md:grid-cols-2"><div><button className="block w-full cursor-zoom-in" onClick={()=>setBox(true)}><Img src={im[i]} alt={ims[i]?.alt||p.name} className="aspect-[4/5]"/></button>
{im.length>1&&<div className="mt-3 flex gap-2 overflow-x-auto">{im.map((u,k)=><button key={k} onClick={()=>setI(k)} className={`h-20 w-16 shrink-0 border ${k===i?'border-ink':'border-transparent'}`}><img src={u} alt={ims[k]?.alt||''} onError={fix} className="h-full w-full object-cover"/></button>)}</div>}
{p.video_url&&<video src={p.video_url} controls playsInline preload="metadata" poster={im[0]!==PH?im[0]:undefined} className="mt-4 w-full bg-black"/>}
{p.model_url&&<ModelView src={p.model_url} name={p.name} poster={im[0]!==PH?im[0]:undefined} label={t('view3d')}/>}</div>
<div className="md:sticky md:top-28 md:self-start"><Link to={p.categories?`/category/${p.categories.slug}`:'/catalogue'} className="text-sm text-earth underline">{p.categories?.name||t('nav_catalogue')}</Link>
<h1 className="mt-2 font-serif text-4xl md:text-6xl">{p.name}</h1>{(p.price_text||p.badge)&&<p className="mt-3 flex items-center gap-3">{p.badge&&<span className="border border-earth px-2 py-0.5 text-xs uppercase tracking-wider text-earth">{p.badge}</span>}{p.price_text&&<span className="font-serif text-2xl">{p.price_text}</span>}</p>}{p.short_description&&<p className="mt-4 text-lg font-light">{p.short_description}</p>}
{p.description&&<p className="mt-6 max-w-prose whitespace-pre-line font-light leading-relaxed">{p.description}</p>}
{rows.length>0&&<dl className="mt-8 border-t border-sand">{rows.map((x,k)=><div key={k} className="flex justify-between gap-4 border-b border-sand py-3 text-sm"><dt className="text-earth">{x.label}</dt><dd className="text-right">{x.value}</dd></div>)}</dl>}
<div className="mt-8 flex flex-wrap gap-3"><Mag><Link to={`/contact?product=${encodeURIComponent(p.name)}`} onClick={()=>track('enquire_click',p)} className="btn">{t('enquire_btn')}</Link></Mag>{wa&&<a className="btn btn-o" target="_blank" rel="noreferrer" onClick={()=>track('whatsapp_click',p)} href={`https://wa.me/${wa}?text=${encodeURIComponent(`Hi, I am interested in ${p.name} ${location.href.split('?')[0]}`)}`}>{t('whatsapp_btn')}</a>}<button type="button" aria-pressed={on} className="btn btn-o" onClick={()=>{L.toggle(p);if(!on)track('save',p)}}><Heart size={16} className="mr-2 inline align-[-2px]" fill={on?'currentColor':'none'}/>{on?t('saved_btn'):t('save_btn')}</button></div></div></div>
{rel.length>0&&<section className="mt-24"><Head t={t('related_heading')}/><div className="grid grid-cols-2 gap-x-4 gap-y-10 lg:grid-cols-4 lg:gap-x-6">{rel.map((x,k)=><Card key={x.id} p={x} i={k}/>)}</div></section>}
<AnimatePresence>{box&&<motion.div initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onClick={()=>setBox(false)} className="fixed inset-0 z-50 flex items-center justify-center bg-black/90 p-4"><button aria-label="Close" className="absolute right-5 top-5 text-white"><X/></button><motion.img initial={{scale:.96}} animate={{scale:1}} src={im[i]} alt={p.name} className="max-h-full max-w-full object-contain"/></motion.div>}</AnimatePresence></Pg>}
export function About(){const s=useSite(),t=useT();return <Pg><h1 className="font-serif text-5xl md:text-7xl">{t('about_heading')} {s.business_name||'us'}</h1><p className="mt-8 max-w-prose whitespace-pre-line font-light leading-relaxed">{s.about_body||'This page can be edited from the admin panel under Business settings.'}</p><Link to="/contact" className="btn mt-8">{t('about_btn')}</Link></Pg>}
export function Contact(){
const s=useSite(),t=useT();const [sp]=useSearchParams();const [st,setSt]=useState('');const t0=useRef(0);useEffect(()=>{t0.current=Date.now()},[])
const defs=Array.isArray(s.form_fields)&&s.form_fields.length?s.form_fields:DEFAULT_FORM
const PH_={name:'ph_name',email:'ph_email',phone:'ph_phone',product:'ph_product',message:'ph_message'},LIM={name:200,email:320,phone:50,product:1000,message:5000}
const lab=d=>d.label||(PH_[d.key]?t(PH_[d.key]):d.key)
const send=async e=>{e.preventDefault();const form=e.target,fd=new FormData(form),f=Object.fromEntries(fd)
if(f.website){setSt('ok');form.reset();return}
if(Date.now()-t0.current<2500){setSt('err');return}
const extra=defs.filter(d=>!PH_[d.key]).map(d=>{const v=d.type==='checkbox'?(fd.has(d.key)?'Yes':'No'):(f[d.key]||'').toString().trim();return v?`${lab(d)}: ${v}`:''}).filter(Boolean)
const msg=[(f.message||'').trim(),...extra].filter(Boolean).join('\n\n').slice(0,4900)||'(no message)'
setSt('sending');const r=await sendEnquiry({name:(f.name||'').trim()||'(no name)',email:(f.email||'').trim()||'(not given)',phone:f.phone,product:f.product,message:msg});if(r==='ok')form.reset();setSt(r)}
const wa=(s.whatsapp||'').replace(/\D/g,'')
const R=({I,children})=>children?<p className="flex gap-3"><I size={18} className="mt-1 shrink-0 text-earth"/><span className="whitespace-pre-line">{children}</span></p>:null
const fld=d=>{const l=lab(d),n=d.key,base={name:n,required:!!d.required,'aria-label':l}
if(d.type==='textarea')return <textarea key={d.id} {...base} rows={5} className="inp" maxLength={LIM[n]||2000} placeholder={l}/>
if(d.type==='select')return <label key={d.id} className="block text-sm">{l}<select {...base} defaultValue="" className="inp mt-1"><option value="" disabled={!!d.required}>—</option>{(d.options||'').split(',').map(x=>x.trim()).filter(Boolean).map(x=><option key={x}>{x}</option>)}</select></label>
if(d.type==='checkbox')return <label key={d.id} className="flex items-center gap-3 text-sm"><input type="checkbox" name={n} required={!!d.required}/>{l}</label>
if(d.type==='date'||d.type==='number')return <label key={d.id} className="block text-sm">{l}<input {...base} type={d.type} className="inp mt-1"/></label>
return <input key={d.id} {...base} type={d.type==='email'||d.type==='tel'?d.type:'text'} maxLength={LIM[n]||500} defaultValue={n==='product'?sp.get('product')||'':undefined} className="inp" placeholder={l}/>}
return <Pg><h1 className="font-serif text-5xl md:text-7xl">{t('contact_heading')}</h1><div className="mt-12 grid gap-12 md:grid-cols-2">
<form onSubmit={send} className="relative space-y-4"><input name="website" tabIndex={-1} autoComplete="off" aria-hidden="true" className="absolute -left-[9999px] h-0 w-0 opacity-0"/>{defs.map(fld)}
<button className="btn" disabled={st==='sending'}>{st==='sending'?'…':t('form_send')}</button>
{st==='ok'&&<p role="status">{t('form_ok')}</p>}{st==='err'&&<p role="alert">{t('form_err')}</p>}{st==='config'&&<p role="alert">Email sending is not set up yet. Add the EmailJS keys to .env.</p>}</form>
<div className="space-y-4 font-light"><R I={Phone}>{s.phone}</R><R I={Mail}>{s.email}</R>{wa&&<p className="flex gap-3"><MessageCircle size={18} className="mt-1 text-earth"/><a className="underline" href={`https://wa.me/${wa}`}>Chat on WhatsApp</a></p>}<R I={MapPin}>{s.address}</R><R I={Clock}>{s.hours}</R></div></div></Pg>}
export function Saved(){const t=useT(),L=useList()
return <Pg><h1 className="font-serif text-5xl md:text-7xl">{t('saved_heading')}</h1>{!L.items.length?<><p className="mt-8">{t('saved_empty')}</p><Link to="/catalogue" className="btn mt-8">{t('nav_catalogue')}</Link></>:<><ul className="mt-10 grid grid-cols-2 gap-4 md:grid-cols-4">{L.items.map(x=><li key={x.slug} className="relative"><Link to={`/product/${x.slug}`}><div className="aspect-[4/5] overflow-hidden bg-sand"><img src={x.img||PH} alt="" onError={fix} className="h-full w-full object-cover"/></div><p className="mt-2 font-serif text-xl">{x.name}</p></Link><button type="button" aria-label={`Remove ${x.name}`} onClick={()=>L.remove(x.slug)} className="absolute right-2 top-2 grid h-8 w-8 place-items-center rounded-full bg-ivory/90"><X size={16}/></button></li>)}</ul>
<div className="mt-10 flex flex-wrap gap-3"><Link to={`/contact?product=${encodeURIComponent(L.items.map(x=>x.name).join(', ').slice(0,1000))}`} className="btn">{t('saved_send')}</Link><button type="button" className="btn btn-o" onClick={L.clear}>{t('saved_clear')}</button></div></>}</Pg>}
export function Visit(){const s=useSite(),t=useT(),[st,setSt]=useState(''),t0=useRef(0);useEffect(()=>{t0.current=Date.now()},[])
const today=new Date(Date.now()-new Date().getTimezoneOffset()*6e4).toISOString().slice(0,10),slots=['slot_morning','slot_afternoon','slot_evening'].map(k=>t(k))
const send=async e=>{e.preventDefault();const form=e.target,f=Object.fromEntries(new FormData(form))
if(f.website){setSt('ok');form.reset();return}
if(Date.now()-t0.current<2500){setSt('err');return}
setSt('sending');const r=await sendEnquiry({name:f.name,email:f.email,phone:f.phone,product:'Showroom visit',kind:'visit',visit_date:f.date,visit_time:f.time,people:f.people||1,message:`Showroom visit request\nDate: ${f.date}\nTime: ${f.time}\nPeople: ${f.people||1}${f.note?`\n${f.note}`:''}`});if(r==='ok')form.reset();setSt(r)}
const R=({I,children})=>children?<p className="flex gap-3"><I size={18} className="mt-1 shrink-0 text-earth"/><span className="whitespace-pre-line">{children}</span></p>:null
return <Pg><h1 className="font-serif text-5xl md:text-7xl">{t('visit_heading')}</h1><p className="mt-4 max-w-prose font-light">{t('visit_intro')}</p><div className="mt-12 grid gap-12 md:grid-cols-2">
<form onSubmit={send} className="relative space-y-4"><input name="name" required maxLength={200} className="inp" placeholder={t('ph_name')} aria-label={t('ph_name')}/><input name="website" tabIndex={-1} autoComplete="off" aria-hidden="true" className="absolute -left-[9999px] h-0 w-0 opacity-0"/><input name="email" type="email" required maxLength={320} className="inp" placeholder={t('ph_email')} aria-label={t('ph_email')}/><input name="phone" type="tel" required maxLength={50} className="inp" placeholder={t('ph_phone')} aria-label={t('ph_phone')}/>
<div className="grid gap-4 sm:grid-cols-2"><label className="block text-sm">{t('visit_date')}<input name="date" type="date" required min={today} className="inp mt-1"/></label><label className="block text-sm">{t('visit_time')}<select name="time" required className="inp mt-1">{slots.map(x=><option key={x}>{x}</option>)}</select></label></div>
<label className="block text-sm">{t('visit_people')}<input name="people" type="number" min={1} max={20} defaultValue={2} className="inp mt-1"/></label><textarea name="note" rows={3} maxLength={1000} className="inp" placeholder={t('ph_message')} aria-label={t('ph_message')}/>
<button className="btn" disabled={st==='sending'}>{st==='sending'?'…':t('visit_send')}</button>{st==='ok'&&<p role="status">{t('visit_ok')}</p>}{st==='err'&&<p role="alert">{t('form_err')}</p>}{st==='config'&&<p role="alert">Sending is not set up yet.</p>}</form>
<div className="space-y-4 font-light"><R I={MapPin}>{s.address}</R><R I={Clock}>{s.hours}</R><R I={Phone}>{s.phone}</R></div></div></Pg>}
export function NotFound(){return <Pg><h1 className="font-serif text-6xl">Page not found</h1><p className="mt-4">The page you are looking for does not exist.</p><Link to="/" className="btn mt-8">Back to home</Link></Pg>}
