create extension if not exists pgcrypto;
create table public.profiles(id uuid primary key references auth.users on delete cascade,is_admin boolean not null default false,created_at timestamptz default now());
create function public.is_admin() returns boolean language sql security definer stable set search_path=public as $$select coalesce((select is_admin from public.profiles where id=auth.uid()),false)$$;
create function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$begin insert into public.profiles(id) values(new.id) on conflict do nothing;return new;end$$;
create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user();
create table public.categories(id uuid primary key default gen_random_uuid(),name text not null check(length(trim(name))>0),slug text not null unique check(slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),description text,image_url text,sort_order int not null default 0,created_at timestamptz default now());
create table public.products(id uuid primary key default gen_random_uuid(),category_id uuid references public.categories on delete set null,name text not null check(length(trim(name))>0),slug text not null unique check(slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),short_description text,description text,status text not null default 'draft' check(status in('draft','published','archived')),featured boolean not null default false,sort_order int not null default 0,created_at timestamptz default now());
create table public.product_images(id uuid primary key default gen_random_uuid(),product_id uuid not null references public.products on delete cascade,url text not null,sort_order int not null default 0);
create table public.product_specifications(id uuid primary key default gen_random_uuid(),product_id uuid not null references public.products on delete cascade,label text not null,value text not null,sort_order int not null default 0);
create table public.homepage_settings(id int primary key default 1 check(id=1),hero_title text,hero_subtitle text,hero_image_url text,story_title text,story_body text,story_image_url text,showcase_image_url text);
create table public.homepage_carousel_items(id uuid primary key default gen_random_uuid(),image_url text not null,caption text,link_url text,sort_order int not null default 0,active boolean not null default true);
create table public.site_settings(id int primary key default 1 check(id=1),business_name text default 'Saloni Furniture',phone text,email text,whatsapp text,address text,hours text,about_body text);
insert into public.homepage_settings(id) values(1);insert into public.site_settings(id) values(1);
create index on public.products(category_id);create index on public.product_images(product_id);create index on public.product_specifications(product_id);
alter table public.profiles enable row level security;
create policy "read own profile" on public.profiles for select using(id=auth.uid());
do $$declare t text;begin foreach t in array array['categories','products','product_images','product_specifications','homepage_settings','homepage_carousel_items','site_settings'] loop execute format('alter table public.%I enable row level security',t);execute format('create policy "admin all" on public.%I for all using(public.is_admin()) with check(public.is_admin())',t);end loop;end$$;
create policy "public read" on public.categories for select using(true);
create policy "public read" on public.homepage_settings for select using(true);
create policy "public read" on public.site_settings for select using(true);
create policy "public read" on public.homepage_carousel_items for select using(active);
create policy "public read" on public.products for select using(status='published');
create policy "public read" on public.product_images for select using(exists(select 1 from public.products p where p.id=product_id and p.status='published'));
create policy "public read" on public.product_specifications for select using(exists(select 1 from public.products p where p.id=product_id and p.status='published'));
insert into storage.buckets(id,name,public) values('product-images','product-images',true) on conflict do nothing;
create policy "admin upload" on storage.objects for insert to authenticated with check(bucket_id='product-images' and public.is_admin());
create policy "admin update" on storage.objects for update to authenticated using(bucket_id='product-images' and public.is_admin());
create policy "admin delete" on storage.objects for delete to authenticated using(bucket_id='product-images' and public.is_admin());
